server {
    server_name nova-maktab.uz www.nova-maktab.uz;
    client_max_body_size 50M;

    root /home/ubuntu/nova/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /socket.io/ {
        proxy_pass http://localhost:5555;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://localhost:5555;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        alias /home/ubuntu/nova/nova-backend/public/uploads/;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/nova-maktab.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nova-maktab.uz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.nova-maktab.uz) {
        return 301 https://$host$request_uri;
    }
    if ($host = nova-maktab.uz) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name nova-maktab.uz www.nova-maktab.uz;
    client_max_body_size 50M;
    return 404;
}
